name: todo_infinity_app
description: A new Flutter project.
#? -------------------------------------------
publish_to: 'none' 
#? -------------------------------------------
version: 1.0.0+1
#? -------------------------------------------
environment:
  sdk: '>=2.18.2 <3.0.0'
#? -------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.2.1
  loading_animation_widget: ^1.2.0+3
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  persian_datetime_picker: ^2.6.0
  dropdown_button2: ^2.0.0
  flutter_screenutil: ^5.7.0
  flutter_slidable: ^3.0.1
  toastification: ^2.2.0
  animated_bottom_navigation_bar: ^1.2.0
  dio: ^5.2.0+1
  step_progress_indicator: ^1.0.2
  validators: ^3.0.0
  device_preview: ^1.1.0
  encrypt: ^5.0.3
  gap: ^3.0.1
  appwrite: ^13.0.0
  flutter_animate: ^4.5.0
  get_it: ^8.0.0
  internet_connection_checker: ^2.0.0
  fpdart: ^1.1.0
  top_snackbar_flutter: ^3.1.0
  awesome_snackbar_content: ^0.1.4
#? -------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#? -------------------------------------------
flutter:
  uses-material-design: true
#? -------------------------------------------  
  assets:
    - assets/images/
    - assets/icons/
#? -------------------------------------------
  fonts:
    - family: Samim
      fonts:
        - asset: assets/fonts/Samim.ttf
          weight: 300
        - asset: assets/fonts/Samim-Bold.ttf
          weight: 700
    - family: Fanavari
      fonts:
        - asset: assets/fonts/Fanavari-Regular.ttf
          weight: 300
        - asset: assets/fonts/Fanavari-Bold.ttf
          weight: 700